### ISSUE TITLE
Category color assignment

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#110]
@davidmanzanares 

While testing the category ramp fix (https://github.com/CartoDB/renderer-prototype/issues/66), I noticed something else that I don't think is expected behavior.

Using some Airbnb data, there are 3 categories of the attribute `room_type`:
`Entire home/apt`, 
`Private room`, 
`Shared room`

Using this syntax:

`color: ramp($room_type,vivid)`

I'd expect to see the first three colors in the scheme `vivid` for each of the types:
<img width="236" alt="screen shot 2018-02-23 at 10 24 14 am" src="https://user-images.githubusercontent.com/1566273/36610075-d2bce7b2-1883-11e8-8dea-f2f8261592b1.png">

Instead, what I'm seeing is [this](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKCRyb29tX3R5cGUsdml2aWQpXG5zdHJva2VXaWR0aDogMVxuc3Ryb2tlQ29sb3I6IGhzdigwLDAsMClcblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExOC4wMzY2MTIwNjM1ODg3OSwibGF0IjozNC4yNTIwMDkyODA4NDc3MTZ9LCJnIjo4LjQyOTAyMzQ4NDU1NTk4N30=) where the first color in the scheme is skipped and the third category `Shared room` being skipped altogether.

<img width="275" alt="screen shot 2018-02-23 at 10 02 04 am" src="https://user-images.githubusercontent.com/1566273/36609107-a7a90126-1880-11e8-8129-5d647e58ce79.png">

On the other hand, if I define the style with `buckets`:

`color: ramp(buckets($room_type,"Entire home/apt", "Private room", "Shared room"),vivid)`

I see the [expected result](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKGJ1Y2tldHMoJHJvb21fdHlwZSxcIkVudGlyZSBob21lL2FwdFwiLCBcIlByaXZhdGUgcm9vbVwiLCBcIlNoYXJlZCByb29tXCIpLHZpdmlkKVxuc3Ryb2tlV2lkdGg6IDFcbnN0cm9rZUNvbG9yOiBoc3YoMCwwLDApXG5cblxuXG5cblxuIiwiZiI6eyJsbmciOi0xMTguMTk4MjcwMDYyODc5ODMsImxhdCI6MzQuMDQ2OTIzMDQ0ODg5NjV9LCJnIjo4Ljg1NTMxNjU4MTA0MzE2Nn0=) for that syntax which is also what I would expect to see in the first rendering.

<img width="287" alt="screen shot 2018-02-23 at 10 01 14 am" src="https://user-images.githubusercontent.com/1566273/36609119-afa5fd3e-1880-11e8-9ba5-2cc731fab541.png">

**Comment by davidmanzanares** [comment]
I think I fixed this, and https://github.com/CartoDB/renderer-prototype/issues/75 , but it would be very good if you could check the new ramp() behavior (not just these two cases). Thank you!

**Comment by makella** [comment]
@davidmanzanares what are the new ramp behaviors?

**Comment by davidmanzanares** [comment]
I hope that the ones that you expected in the first place. I'm saying this because the fix included relatively important changes that affect all maps that are styled by category, not just ramps, actually, and I'm not very confident in the solution :joy:

**Comment by makella** [comment]
ohhhh ok. I'll go through all my category map types and check them!

**Comment by makella** [comment]
heyy @davidmanzanares 

Ok, so I went through the cateogry maps.

`color: ramp($room_type,vivid)`: **Fixed!**
+ [Map Link](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKCRyb29tX3R5cGUsdml2aWQpXG5zdHJva2VXaWR0aDogMC41XG5zdHJva2VDb2xvcjogaHN2KDAsMCwwKVxuXG5cblxuXG5cbiIsImYiOnsibG5nIjotMTE4LjEzODM3OTAyNDM2ODQ4LCJsYXQiOjM0LjEyMjMwMzk4MzEyODY3NH0sImciOjkuMzQ0NTE1MTA2MDg5MzQxfQ==)

`color: ramp(top($neighbourhood,4),prism)` : **Looks good**

+ [Map Link](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKHRvcCgkbmVpZ2hib3VyaG9vZCw0KSxwcmlzbSlcbnN0cm9rZVdpZHRoOiAwLjVcbnN0cm9rZUNvbG9yOiBoc3YoMCwwLDApXG5cblxuXG5cblxuIiwiZiI6eyJsbmciOi0xMTguMjg4NTgwODMzOTU3MjEsImxhdCI6MzQuMTUyMjQ4NDk4NTIzNDJ9LCJnIjo4LjUzNzU2MDgyMjIwNzg4OH0=)

Two that I want to take a closer look at in the morning to understand better what is happening. To be honest, I kind of like these results but want to take a deeper look over multiple datasets to figure out the pattern better.

`color: ramp(MODE($neighbourhood_cleansed),Prism)`

_I think there are over 200 neighborhoods defined... will test over different datasets_

+ [Map Link](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKCRuZWlnaGJvdXJob29kX2NsZWFuc2VkLHByaXNtKVxuc3Ryb2tlV2lkdGg6IDAuNVxuc3Ryb2tlQ29sb3I6IGhzdigwLDAsMClcblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExOC4yNTI4MjgyMTEzNTAyMiwibGF0IjozNC4yNDEwOTA2Mjg0NzQ2OTR9LCJnIjo5LjI4OTE4MjI4ODE4ODY3OX0=)

`color: ramp($neighbourhood,prism)`
+ [Map Link](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKCRuZWlnaGJvdXJob29kLHByaXNtKVxuc3Ryb2tlV2lkdGg6IDAuNVxuc3Ryb2tlQ29sb3I6IGhzdigwLDAsMClcblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExOC4zNjMyMTAxNDE5NTE3LCJsYXQiOjM0LjEzMzEwNDQwOTQ2Njk5NX0sImciOjExLjkxODY1NjEyNDExOTEzOH0=)

Ok! I'll dig deeper tomorrow.

**Comment by makella** [comment]
@davidmanzanares the initial issue of colors being skipped in category schemes seems to be fixed. 

I still don't understand exactly what is happening with colors being interpolated with category schemes (when there are many categories) and seeing different behaviors depending on the schemes. Will post in another issue.

**Comment by davidmanzanares** [comment]
@makella

Nice! Closing this one!

Feel free to open another issue about related things. When there are more categories than cartocolors the renderer choose the palette with most colors available and it linearly interpolates between those. I think this is a good behavior in general, but it can be broken (bad implementation) and there can be many corner cases that aren't being looked upon.

**Comment by makella** [comment]
@davidmanzanares opened another issue with some questions (https://github.com/CartoDB/renderer-prototype/issues/129). Can you give me a deeper dive into the linear interpolation between colors? Maybe you have explained it to me before but I am seeing really weird results.
