### ISSUE TITLE
Define and document an end-user API

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#13]
Right now, the styling API is relatively mature, but other parts of the API are just a WIP.

The API should take, at least, into account:

-  Sources (dataset, SQL)
-  Layers
-  Style as  a set of styling root expressions
-  Interactivity: getFeatureBehindCursor, getFeaturesInBBox, getFeaturesInViewport, change style for one or more particular features, eg: `feature.style.color.blendTo(R.rgba(0,0,0,0.5)`

**Comment by Jesus89** [comment]
Duplicated: https://github.com/CartoDB/renderer-prototype/issues/43
