### ISSUE TITLE
Improve expression naming

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#139]
I think that the following changes should be done:
floatAdd => add
...
floatSub => sub
property => prop
float => number

**Comment by IagoLast** [comment]
+1

**Comment by Jesus89** [comment]
Closed by #142

**Comment by davidmanzanares** [comment]
:+1:

**Comment by davidmanzanares** [comment]
"float => number" hasn0t been done yet

**Comment by Jesus89** [comment]
Done: https://github.com/CartoDB/renderer-prototype/commit/ba97707643ef5ad4d8e8724000fda84394a9585c

**Comment by davidmanzanares** [comment]
It would require docs too :slightly_smiling_face:

**Comment by IagoLast** [comment]
@Jesus89 update float docs with the new alias ;)

**Comment by Jesus89** [comment]
https://github.com/CartoDB/renderer-prototype/commit/9520e2f83ae75562583fadf079cccf494c4add2d :book:
