### ISSUE TITLE
Reduce documentation expectations

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#140]
I think we should use jsdoc just for the public API. It is too verbose/explicit for documenting private methods. Although I think that comments / documentation is sometimes the best way to make something clear, in general, self-documented code is a good approach, custom regular comments when that is not enough is what I think we should do.

cc: @IagoLast

**Comment by IagoLast** [comment]
>  self-documented code

100% agree, we should focus on creating a clean, well structured and easy to read code

> I think we should use jsdoc just for the public API

jsdoc gives some extra points, for example vscode can infer parameter types and shows hints and method descriptions.

The problem here is the code structure is kinda weird so jsdoc needs some help.

**Comment by davidmanzanares** [comment]
A small comment, internal types could be managed by a real solution like typescript.
