### ISSUE TITLE
Allow more than 4 properties

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#154]
The current implementation only allows 4 properties to be read simultaneously. This is a renderer limit, although sources should be modified by this too.

WebGL imposes some limits regarding texture units, but the limit is higher, although texture units are shared with ramp() textures and other expression textures too.

We need to dynamically use as much TUs as we need and throw an error if the required number of textures is higher than the WebGL implementation limit.

**Comment by rochoa** [comment]
PR https://github.com/CartoDB/renderer-prototype/pull/241
