### ISSUE TITLE
Quantiles not working

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#163]
@davidmanzanares 

any idea why quantiles isn't working in this example map?

https://cartodb.github.io/renderer-prototype/examples/expressions/ramp-numeric.html

**Comment by davidmanzanares** [comment]
Yes, because classification of polygons and lines is still unsupported, I've updated https://github.com/CartoDB/renderer-prototype/issues/11 to keep track of this there

**Comment by makella** [comment]
ahhh!! sorry david! forgot :/
