### ISSUE TITLE
Check CI environment

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#174]
- Investigate CircleCI option to return true even if the test fails (for the acceptance tests). If this is not possible we will keep the e2e tests out of the CI.
-  Investigate CircieCI to enable `pr/push` testing. If this is possible we can disable TravisCI.

**Comment by Jesus89** [comment]
CircleCI does not have the `Build pushed pull requests` option as in TravisCI:

![selection_081](https://user-images.githubusercontent.com/2227572/37465237-e40a8b8c-285a-11e8-812d-f83f449a3fee.png)

Now we are testing only the unit tests in Travis. This is already tested in the `lint` and `test-unit` jobs in CircleCI, so I think we could disable the `Build pushed branches` option.

If we want to keep the `Build pushed pull requests` testing, the only way is to use TravisCI. Otherwise we can disable both.

What do you think?

cc @IagoLast @davidmanzanares @rochoa @jgoizueta

**Comment by IagoLast** [comment]
Im not sure about if I understand what each option do

**Comment by Jesus89** [comment]
Regarding the `silent` e2e testing. We can add `|| true` to the command and it will always return true:
```
- run: xvfb-run -a yarn test:e2e || true
```

But if the test really fails (not because of the server timeout) we won't detect it. Always green -> useless.

IMO covering windshaft client with proper unit tests is the real solution.

**Comment by Jesus89** [comment]
**Bonus**

I think we could cover the doc generation (`yarn docs`) in the linter job.

**Comment by IagoLast** [comment]
> I think we could cover the doc generation (yarn docs) in the linter job.

In a paralel task

**Comment by davidmanzanares** [comment]
@IagoLast Keep in mind CircleCI concurrent jobs limit. We could parallelize a lot, but since each job has a constant initialization cost, it may be better to have just a few jobs.

**Comment by IagoLast** [comment]
as you wish

**Comment by Jesus89** [comment]
> Im not sure about if I understand what each option do

`Build pushed branches` is for building all the commits.
`Build pushed pull requests` checks the PR merged with master.

I think we should include docs checking in the linter job because it is a linter for the documentation (and it takes only **1 sec** :P)

**Comment by Jesus89** [comment]
OK so final recap:
- Remove TravisCI (both options). Keep in mind that we were using Travis only for the unit tests.
- Keep acceptance tests out of CI
- Include `yarn docs` in the linter job

**Comment by Jesus89** [comment]
Closed:
![selection_082](https://user-images.githubusercontent.com/2227572/37471436-f7fe9570-2869-11e8-87b9-3b48b1405cd1.png)

- 26f7d8562beb82269d27fa03ea1c68fbe1067b7d
