### ISSUE TITLE
Add Style to Feature object (+docs + tests)

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/renderer-prototype#202]
Related to #61 

Proposed api
----

- Feature
  - resetStyle()
   - getStyle(): style
     - getColor()
     - blendToColor()
     - setColor(color)
     - resetColor()
     - getWidth()
     - blendToWitdh()
     - setWidth(color)
     - resetWidth()
     - getStrokeWidth()
     - blendToStrokeWidth()
     - setStrokeWidth(color)
     - resetStrokeWidth()
     - getStrokeColor()
     - blendToStrokeColor()
     - setStrokeColor(color)
     - resetStrokeColor()

**Comment by davidmanzanares** [comment]
Done: https://github.com/CartoDB/renderer-prototype/pull/232
