### ISSUE TITLE
Can we add current zoom level to the editor?

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#205]
While testing zoom based interpolation, it would be super helpful to relate the current map view to a  zoom level. 

For my testing purposes, would it be possible to get the zoom level written out on the interface somewhere?

thanks!

**Comment by makella** [comment]
@IagoLast not sure I see this in the editor... am I missing something?

thanks!

**Comment by Jesus89** [comment]
It is displayed in the bottom-left corner

![selection_128](https://user-images.githubusercontent.com/2227572/38428664-9e7878ea-39bc-11e8-8074-2963b6483d25.png)

**Comment by makella** [comment]
aha!!

totally missed it...

thank you!!
