### ISSUE TITLE
Buckets() for categories

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#23]
Support `color: ramp(buckets($type, 'typeA', 'typeB', typeC'), [red, green, blue, gray])`

**Comment by davidmanzanares** [comment]
Since it was related I fixed `top()` too:
Before:
![before](https://user-images.githubusercontent.com/1692175/36095398-5da9b1ec-0ff2-11e8-8567-b23c039914d5.png)
After:
![after](https://user-images.githubusercontent.com/1692175/36095397-5d8ff504-0ff2-11e8-9c21-8b1bb4cd0fd8.png)
New feature:
![newbuckets](https://user-images.githubusercontent.com/1692175/36095399-5dc49fca-0ff2-11e8-9443-9c2404cd45f2.png)

Tested with 
```
width: 3
color: ramp(buckets($category, "Moda y calzado", "Bares y restaurantes", "Salud"), Prism)
```

Not deployed yet

**Comment by makella** [comment]
nice!
