### ISSUE TITLE
Fix crashing bug on Mac

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#233]
DESCRIPTION
--- 

The system dies after opening the renderer 🍞

### AFFECTED DEVICES

```
MacBook Pro (Retina, 13-inch, Early 2015)
10.12.6
Intel Iris Graphics 6100 1536 MB
```

### COMMITS
804a44bf85fd88b2ab490a935a11a7700b4b43db --> 🆗 (tested for 10 minutes without errors)
f24bedf8160a5ca164d7eab43cf5ea64cab09f7b ---> 💥 (tested for 5 seconds and crash)

RESEARCH
--- 

In `renderer.js` we have the following likes that change the renderer viewport size.

```js
const gl = this.
const width = gl.canvas.
const height = gl.canvas.clientHeight;

if (gl.canvas.width != width || gl.canvas.height != height) {
  gl.canvas.width = width;
  gl.canvas.height = height;
}
```

As you can see [here](https://github.com/CartoDB/renderer-prototype/commit/f24bedf8160a5ca164d7eab43cf5ea64cab09f7b#diff-ba2b399628ae0c09a9b06d41faff9b64R279) we add an early-return condition where data was not loaded.

```js
if (!tiles.length) {
  return;
}
```

This return prevents the following command to be executed:

```js
gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight);
```

Leading to an inconsistent state that crashes the system.

So we need to be sure of calling `gl.viewport` before returning the control to fix the bug, another option is not to change the canvas size manually.

cc @davidmanzanares @rochoa @Jesus89

**Comment by rochoa** [comment]
BTW, I was not able to hit the problem. My setup:

![screen shot 2018-03-27 at 19 40 21](https://user-images.githubusercontent.com/45346/37984568-e0f7bfc8-31f6-11e8-9832-6cab960068fd.png)

**Comment by IagoLast** [comment]
It looks the bug starts here 1d373ec773d467e6aa32b2040f0c7263336742e6

(need more testing)
