### ISSUE TITLE
Colors as first class citizens

### ISSUE THREAD

**Issue by davidmanzanares** [CartoDB/renderer-prototype#24]
Minimum support:
- [x] RGB
- [x] RGBA
- [x] Hex: '#FFF'
- [x] HSL
- [x] HSLA
- [x] HSV
- [x] HSVA
- [x] Named colors: red, green, blue, (...)

cc: @makella

**Comment by rochoa** [comment]
@makella, if you had to decide what are the top 5 to support for an initial version, which ones would you pick?

**Comment by makella** [comment]
without taking color interpolation into account, for basic, basic, I'd do:

- rgb
- rgba
- HSL (easier notation than HSV)
- HSLa
- HSV (since we have examples that utilize)
- HSVa
- named colors

**Comment by davidmanzanares** [comment]
Just to be sure, you mean HSL, not HSLuv, right?

If that's the case, those shouldn't be a problem at all.

**Comment by makella** [comment]
ahhhh!! right

is it complicated? i do prefer HSLuv... for the reasons we talked about (thanks for the reminder)

**Comment by davidmanzanares** [comment]
I found a GLSL implementation: https://github.com/williammalo/hsluv-glsl/blob/master/hsluv-glsl.fsh
and a C (similar to GLSL) implementation: https://github.com/hsluv/hsluv-c/blob/master/src/hsluv.c

If those implementations are good it shouldn't be difficult to adapt it. But I would do the rest of your list first since they are even easier.

**Comment by rochoa** [comment]
No hexadecimal (e.g. #FFF) notation?

**Comment by makella** [comment]
@rochoa OMG totally had it and then re-ordered the list and deleted it!

gooood catch!

update:
- rgb/rgba
- HSL/HSLa (easier notation than HSV)
- HSV/HSVa (since we have examples that utilize)
- HSLuv (if possible this is important for color-based expressions)
- HEX
- named colors

**Comment by makella** [comment]
just to summarize, we now have:

+ rgb/rgba
+ HSV/HSVa (since we have examples that utilize)
+ HEX
+ named colors
+ cie lab

is this right?

**Comment by Jesus89** [comment]
We have also HSL/HSLa :)
