### ISSUE TITLE
Final name and project overview

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/renderer-prototype#245]
- [x] [Name](https://docs.google.com/document/d/1eCdg9_ah8bpJcIclSbT6L_ELAAqFbV7K7Ws2cTMZup8/edit?usp=sharing)
- [x] Name spelling: **CARTO VL** or ~CartoVL~ 
- [x] [Project Overview](https://docs.google.com/document/d/1eCdg9_ah8bpJcIclSbT6L_ELAAqFbV7K7Ws2cTMZup8/edit#heading=h.t4c17datr6nw)

**Comment by arianaescobar** [comment]
BOOM! 💥 Done!

**Comment by makella** [comment]
yay!!
now we need tshirts! haha
