### ISSUE TITLE
Varying transparency levels and flashing between features (in "style a feature" example)

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#258]
This might be a known issue, but while working on the `style-feature.html` example (in the [`interact-examples`](https://github.com/CartoDB/renderer-prototype/blob/interact-examples/examples/interactivity/style-feature.html) branch), I'm noticing that the features on the map have varying levels of transparency and when I zoom in and out, I'm seeing some bouncing and flashing:

![transparency-flash](https://user-images.githubusercontent.com/1566273/38272671-19961870-3747-11e8-83d0-31ee58d71735.gif)

The same map in the editor is OK:
https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoid29ybGRfcG9wdWxhdGlvbl8yMDE1IiwiYiI6IiIsImMiOiJjYXJ0b2dsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogNTAqc3FydCgkcG9wXzIwMTUpL3NxcnQoZ2xvYmFsTWF4KCRwb3BfMjAxNSkpKnpvb20oKVxuY29sb3I6IGhzdmEoMC43MywwLjY5LDAuODksMC40KVxuc3Ryb2tlQ29sb3I6IGhzdmEoMC43MywwLjY5LDAuODksMC41KVxuc3Ryb2tlV2lkdGg6IDFcbm9yZGVyOiBhc2Mod2lkdGgoKSlcblxuXG5cblxuXG5cbiIsImYiOnsibG5nIjotNi45MzYzMTgwODg3NDA5MDQsImxhdCI6MTEuMTg1ODgxMDM1MTAwNjY0fSwiZyI6Mi4yMDA1OTUyNDI0MjI3NDd9

**Comment by Jesus89** [comment]
Yes this is a bug. Adding another gif.

![opacity-changes](https://user-images.githubusercontent.com/2227572/38298674-4f006b58-37f8-11e8-9539-68e49e652d16.gif)

**Comment by davidmanzanares** [comment]
The bug is caused by `      order: asc(width())`. I'm going to look into it, removing it in the meantime will solve the issue. I'm not going to create a new issue since there is already an issue with a related `order` problem which is probably the same bug.
