### ISSUE TITLE
support for "flipping" the color scheme

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#33]
This is for when people use a dark map vs. a light map and sequential color schemes. 

With a dark map, many times it is preferable to have the light = more to bring out contrast against the dark background whereas on a light map, light = less.

Is there something we can do to support this in the renderer? 

This functionality is available in Builder forms but [not a part of TurboCarto syntax](https://github.com/CartoDB/turbo-carto/issues/35). If a user clicks the arrow to flip, TC literally reads the scheme colors in backwards and that's how the hex values are listed in the CartoCSS.

![flip-ramp](https://user-images.githubusercontent.com/1566273/35926551-a9c0c630-0be5-11e8-8988-32dc77dc7769.gif)

**Comment by davidmanzanares** [comment]
inverse() is already there!

**Comment by makella** [comment]
nice!!

so what category of operator would this be?

I know we had a category of `Color Constructors` -- being able to manipulate things like `h,s,v` channels... do you think this is part of that?

**Comment by makella** [comment]
@davidmanzanares 

So looking at this closer... do you mean that by default we read in the `inverse()` of a sequential scheme?

I ask because that is the default behavior I'm seeing.

For example, using the Airbnb data's `price` attribute the higher value listings, by default, are colored with the lightest color in the scheme `Emrld`:
<img width="170" alt="screen shot 2018-02-23 at 11 41 39 am" src="https://user-images.githubusercontent.com/1566273/36613532-9612b688-188e-11e8-8e31-d1f4e657bcff.png">


`color: ramp(quantiles($price,7),Emrld)`: [result](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDdcbmNvbG9yOiByYW1wKHF1YW50aWxlcygkcHJpY2UsNyksRW1ybGQpXG5zdHJva2VXaWR0aDogMVxuc3Ryb2tlQ29sb3I6IGhzdigwLDAsMClcblxuXG5cblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExOC4yMDk4MjcyMjk0MTE5OSwibGF0IjozNC4wNDE5Mzk1Mzg3MTE5N30sImciOjguNDk0Mjc3MzUzNjUzNTI2fQ==)

with `inverse()`:
`color: ramp(quantiles($price,7),inverse(Emrld))`: [result](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDdcbmNvbG9yOiByYW1wKHF1YW50aWxlcygkcHJpY2UsNyksaW52ZXJzZShFbXJsZCkpXG5zdHJva2VXaWR0aDogMVxuc3Ryb2tlQ29sb3I6IGhzdigwLDAsMClcblxuXG5cblxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTExOC4xNjk5MTQ1Njg0MDMzOSwibGF0IjozMy45OTg5MTA1NTk5Njg4MDZ9LCJnIjo4LjA3MTQyNzc2Njc0ODUzM30=)

Let's discuss this because from a  "traditional" standpoint, people will expect the `inverse()` result as the default vs. the way we have it now.

**Comment by davidmanzanares** [comment]
Sorry for the delay, I forgot about this.

No, I don't think this could be considered part of `Color Constructors`. I would say this is part of `palettes`, I think it would be good to explain this after explaining how cartocolors can be used with ramps, also near custom palettes (something that hasn't been implemented yet).

About reading in the inverse order, we get the order from cartocolors, but it is certainly possible that that order was meant to be read in the other way.
Does this inversion happen in all cases (all cartocolos, numeric properties, categorical properties...)?
Inverting this is easy, but, if it doesn't need to be inverted in all cases, we would need more details.

**Comment by makella** [comment]
@davidmanzanares no prob!

Let's talk about this next week... they were flipped in cartocolor.js for Builder (long story that I need to refresh myself on)

**Comment by makella** [comment]
After looking deeper david thinks this might have to do specifically with `quantiles` as linear is giving the expected result:

[Linear example](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibGlzdGluZ3MiLCJiIjoiIiwiYyI6Im1hbWF0YWFrZWxsYSIsImQiOiJodHRwczovL3t1c2VyfS5jYXJ0by5jb20iLCJlIjoid2lkdGg6IDVcbmNvbG9yOiByYW1wKGxpbmVhcigkcHJpY2UsNSw1MDApLEVtcmxkKVxuc3Ryb2tlV2lkdGg6IDFcbnN0cm9rZUNvbG9yOiBoc3YoMCwwLDApXG5cblxuXG5cblxuXG5cblxuIiwiZiI6eyJsbmciOi0xMTguNDUzNTU3OTUzMDQ5NDMsImxhdCI6MzQuMzUzMTk0OTQxMjc4MjJ9LCJnIjo4LjQ5NDI3NzM1MzY1MzUyNn0=)

**Comment by davidmanzanares** [comment]
I found the bug, `quantiles` assigned incorrectly the last bucket. Should be already fixed on ghpages now. :rocket:

**Comment by makella** [comment]
Nice, checked, and looks good to me!

thanks, david!
