### ISSUE TITLE
Support for additional basemaps in demo

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#35]
@dv343 

As discussed, in the renderer interface that I'm using, would it be possible to add the additional CARTO basemaps?

Dark Matter: labels under, no labels
Positron: labels on top, labels under, no labels
Voyager: labels on top, labels under, no labels

thanks!

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/renderer-prototype/pull/85

**Comment by makella** [comment]
thank you!
