### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#38]
- [ ] Add a .travis.yml file
- [ ] Setup this project in Travis

NOTE: this project is private. We need to take this into account for Travis.

**Comment by davidmanzanares** [comment]
We need to make sure in the tests that the commit/branch/pr can be correctly be published to gh-pages by issuing a `build-dev` and particularly `build-docs`

**Comment by Jesus89** [comment]
@davidmanzanares Do we need to automate examples/doc deploys to `gh-pages`?

**Comment by davidmanzanares** [comment]
I don't think so, there is a npm script `ghpublish` already present. I prefer to leave a manual switch to "deploy" master just when we want to, although it should be frequent.

**Comment by davidmanzanares** [comment]
I think we could close this issue, travis is already set-up, we just lack tests.

**Comment by Jesus89** [comment]
Closed by: https://github.com/CartoDB/renderer-prototype/commit/56b3552df3c1a42d91b9e9cbbb91e1f94c5b709e
