### ISSUE TITLE
Define lib compatibility

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#45]
Manual QA testing for 18th April version:
- [ ] Browsers support
    - [ ] Chrome
    - [ ] Firefox
- [ ] Platforms
  - [ ] Windows: Nvidia, AMD, Intel.
  - [ ] Mac: AMD, Intel.
  - [ ] Linux: Intel, Nvidia.
- [ ] Acceptance criteria: manual testing of all acceptance tests.

Public version, date TBA:
 - [ ] Browsers
    - [ ] Safari
    - [ ] Opera
    - [ ] Edge
    - [ ] IE
 - [ ] Mobile
   - [ ] TBD

**Comment by Jesus89** [comment]
Hi guys, what about this one?

What browsers (+mobile) do we want to support? This is required to do the "Integration tests"(https://github.com/CartoDB/renderer-prototype/issues/39).

cc @davidmanzanares @IagoLast @rochoa @inigomedina

**Comment by IagoLast** [comment]
Following the [mapbox approach](https://www.mapbox.com/help/mapbox-browser-support/) and Iñigo advice I vote for a reactive approach

"We support modern desktop and mobile browsers"

**Comment by davidmanzanares** [comment]
From your link: 
> specifically:
Safari 9 and above.
Chrome latest.
Firefox latest.
Microsoft Edge 13 (with the most recent Windows 10 update).

IMO, we should do the same.

However, there is another related issue: not all WebGL compatible devices have the same capabilities nor driver implementation. These difference can break WebGL renderers easily, we need to define a list of devices with drivers too. I propose at least:

Desktop:
- Windows with Intel GPU
- Windows with Nvidia GPU
- Windows with AMD GPU
- Mac with Intel GPU
- Linux with Intel GPU
- Linux with Mesa CPU emulation

Mobile:
- Relatively old Android
- Relatively old iPhone

**Comment by IagoLast** [comment]
@davidmanzanares define  `Relatively old` (did u mean Relatively new ?)

**Comment by davidmanzanares** [comment]
@IagoLast I meant `relatively old`. I meant that because on my initial tests I found that it works nicely on really modern phones like an LG G6, but rendering breaks on not so old, yet older, phones.

**Comment by rochoa** [comment]
Check https://saucelabs.com/.

**Comment by inigomedina** [comment]
The Mapbox approach is a very good one for us as a starting point. Good points in there:

- it describes specifically which browsers it supports
- it describes the features those typical browsers have in terms of graphics, hardware, etc.
- it explains that support is not guaranteed in browsers with an experimental support of WebGL
- it gives links to external websites to check your browser
- it even gives an example in the documentation to check your browser

So many good points we can just replicate. Just that would be a huge starting point.

**Comment by Jesus89** [comment]
I move this information to our [main document](https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w/edit) se we can close this ticket.
