### ISSUE TITLE
Opacity and rgba()

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#52]
@davidmanzanares 

is it expected behaviour that `opacity: 0.5` (for example) doesn't work if color is defined in `rgba()` where `a=1`?

**Comment by davidmanzanares** [comment]
This is expected behavior, since `opacity` is not a valid style property. It is just ignored.

This should probably send an error to avoid confusion.

Having a `opacity` property is possible, but it can create confusion too because then, what happens if there is something like:
```
color: opacity(hsv(1,1,1), 0.75)
opacity: 0.5
```
Will the `opacity` override the `0.75`?

**Comment by makella** [comment]
ohhh wait, i thought opacity was a style property! i don't know how i thought that.

soooo what i'm thinking then is it would be good to have opacity as a separate styling property to avoid long and potentially confusing styling.

for example, 

```
color: hsv(1,1,1)
opacity: 0.5
```
do you see any issues with something like that?

**Comment by davidmanzanares** [comment]
Well... in that example you could use https://github.com/CartoDB/renderer-prototype/issues/24
```
color: hsva(1,1,1,0.5)
```
Which to me sounds even better.

For ramps however, the options are 
```
color: ramp($prop, prism)
opacity: 0.5
```
 or 
```
color: opacity(ramp($prop, prism), 0.5)
```

I understand that the first one is more CartoCSS-like, but it creates some complex overriding rules, unless you removed the alpha channel completely from the `color` expression. What do you think about that?
We would have a valid
```
color: ramp($prop, prism)
opacity: 0.5
```
and
```
color: opacity(ramp($prop, prism), 0.5)
```
would be invalid (the opacity could only be changed with `opacity:` not within `color:`

**Comment by makella** [comment]
right, right re: `hsva`

so if you use `rgba, hsva, hsla, etc(a)....` that would be with the `color:` property but you are saying if we moved `opacity:` to its own property, then we would just do away with `rgba, hsva, hsla`, right?

for me, I think that having `opacity:` as its own property feels right... like if I want to do some expression on `opacity`, I wouldn't have to nest it inside my `color:` property and having the two separate, feels like it would be easier to manage the more advanced use cases...

**Comment by makella** [comment]
but don't you think if someone used `rgba, hsva,...` that they would realize that is the alpha channel and to not use `opacity`?

**Comment by davidmanzanares** [comment]
Yes, my last idea would remove `rgba, hsva, hsla, etc(a)....`

Yes, people can understand overriding rules, but I think they are error-prone, and, in any case, it adds complexity to the renderer too.

We can implement color with alpha channel and a opacity overriding property, but, to be honest, I would prefer a simplification, whatever that means avoiding `opacity:` or removing the alpha channel from `color:`

**Comment by makella** [comment]
you know, david... i just thought about something else. like line opacity... would that then have to be another property `strokeOpacity`?

thinking through...

**Comment by makella** [comment]
and totally agree re: simplification! let's definitely talk through this to figure out what makes most sense

**Comment by davidmanzanares** [comment]
`strokeOpacity` Exactly! I didn't think about this, but this is another problem, it wouldn't be good to have colors with alpha, strokeOpacity, fillOpacity and opacity

**Comment by elenatorro** [comment]
Hi :) I am writing a comment here just to point how opacity and alpha channels usually work in CSS. Of course, this is totally different to CSS, but since maybe many users would use the renderer having this field of knowledge, it may be possible that they expect the same behaviour. 

- When using an alpha channel with rgba (or hsla), this opacity value is applied **only** in the property it refers to (i.e: the border, the background, the font...)
- When using the `opacity` property, the opacity value applies to all the elements.

I have no idea how this affects the renderer and, AFAIK, since it works in layers, we may not need to have an opacity property. I wanted to add this information just in case it could be useful :) Thanks!

**Comment by makella** [comment]
@elenatorro yes! thank you for the info!! actually, in CartoCSS the same :) and I actually take advantage of it often, especially with overlapping features.

so in this logic, we would need overall `opacity` and another for each styling property as david mentions above.

but another issue this brings to the table is that we only have `color:` and `strokeColor` where `color` can be applied to polygons, lines, and points... we _might_ need `fillColor`, `pointColor`, etc...

**Comment by davidmanzanares** [comment]
Thanks @elenatorro ! you reminded me of the opacity layer @makella talked with me some time ago, this is not the same as feature opacity and would require its own property for sure.

So... another problem on the table :joy:

**Comment by rochoa** [comment]
So, options we have:
 - Delegate everything to the user: `rgb` vs. `rgba`, or `hsv` vs `hsva`, for each property that supports a colour.
 - Support an `opacity` property that affects all other colour properties.
 - Have more granular properties à la `*Opacity` that affects just the `*` colour property: e.g. `fillOpacity` or `strokeOpacity`.
 - All the above.

What takes precedence? In [Carto]CSS the Cascade part it's clearly defined, but what do we do here? The last (or the most-outer-expression depending on how you use the API) property has precedence? Or opacity uses blending? Additive or Multiplicative? 🤔

I would love to know how going with the simplest approach (delegate everything to the user?) could affect us in the future. Can we implement just that now and later introduce the other options without compromising the API? Do you find acceptable to just have the first option at the beginning?

**Comment by davidmanzanares** [comment]
As we've talked the current `opacity()` as a function is good enough for now and layer opacity is not a priority either, right?

**Comment by makella** [comment]
yes. let's close this for now.
