### ISSUE TITLE
rgba values should be 0-255 vs. current 0-1

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#53]
For a simple point map with color, I am using the following:

```
width: 3
color: rgba(133,75,227,1)
```

https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiYmlnX2RhdGFfZXhhbXBsZVxuIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogICAzXG5jb2xvcjogcmdiYSgxMzMsNzUsMjI3LDEpXG5cblxuXG5cbiIsImYiOnsibG5nIjotMTA1LjMxOTkyMDMwMDQzMTcsImxhdCI6NDkuOTA5OTkyNDM5NTAyODQ0fSwiZyI6Mi45NDgxOTQxNzY0NDk5MjE4fQ==

On the other hand, if I define that color in `hsv` I see it:
https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiYmlnX2RhdGFfZXhhbXBsZVxuIiwiYiI6IjRkMjEyMzc1Mzg2YmFmMWEwOWJiODI2MDhjNjQ4MjE4OGRhM2E1YjAiLCJjIjoibWFtYXRhYWtlbGxhIiwiZCI6ImNhcnRvLmNvbSIsImUiOiJ3aWR0aDogICAzXG5jb2xvcjogaHN2KDAuNzMsMC42OSwwLjg5KVxuXG5cblxuXG4iLCJmIjp7ImxuZyI6LTEwNS4zMTk5MjAzMDA0MzE3LCJsYXQiOjQ5LjkwOTk5MjQzOTUwMjg0NH0sImciOjIuOTQ4MTk0MTc2NDQ5OTIxOH0=

any ideas?

**Comment by davidmanzanares** [comment]
Actually, this is expected behavior, rgba works on the 0 to 1 range, not on the 0 to 255 range.

Please, modify this issue if you think that the 0 to 255 range is better.

**Comment by makella** [comment]
yes! 0-255 please!

**Comment by makella** [comment]
and modified title

**Comment by davidmanzanares** [comment]
Fixed by https://github.com/CartoDB/renderer-prototype/commit/9d2fb714543bec08356c3c8b4873b23f134ec116
