### ISSUE TITLE
Points style properties

### ISSUE THREAD

**Issue by rochoa** [CartoDB/renderer-prototype#54]
Minimum properties to support for point geometries:
 - [x] Size/width.
   - [x] Example.
 - [x] Fill-color.
   - [x] Example.
 - [x] Fill-opacity — do we want to separate fill from stroke opacity?
   - [x] Example.
 - [x] Stroke-size.
   - [x] Example.
 - [x] Stroke-color.
   - [x] Example.

Nice to have:
 - [x] Stroke-opacity?
 - [ ] Size-height?

cc @makella

**Comment by makella** [comment]
looks good to me
