### ISSUE TITLE
Smart backend aggregations expressions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/renderer-prototype#58]
Support [aggregations from CARTO Maps API](https://carto.com/docs/carto-engine/maps-api/tile-aggregation/). Points sources/layers should have expressions to take advantage of those aggregations:

 - [x] max(numeric).
 - [x] min(numeric).
 - [x] avg(numeric).
 - [x] sum(numeric).
 - [x] mode(category).

**Comment by davidmanzanares** [comment]
@rochoa This is already done :confused:

**Comment by davidmanzanares** [comment]
Done!
