### ISSUE TITLE
API: Source, Style, Layer, and Defaults (auth + config)

### ISSUE THREAD

**Issue by rochoa** [CartoDB/renderer-prototype#59]
Continue the work initiated in the [existing document about the API](https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w/edit#heading=h.f5e488fo1ndw).

This should cover the API for:
 - [ ] Default setup: auth and endpoint configuration.
 - [ ] Source model.
 - [ ] Styles.
 - [ ] Layers.

Testing:
 - [ ] It also must describe how we plan to test these entities.

If possible, try to generate this from code. cc @inigomedina

**Comment by Jesus89** [comment]
I'm already on it. Is this ticket duplicated? https://github.com/CartoDB/renderer-prototype/issues/43

**Comment by rochoa** [comment]
Indeed.
