### ISSUE TITLE
API for Expressions

### ISSUE THREAD

**Issue by rochoa** [CartoDB/renderer-prototype#60]
- [x] Define the [API for expressions as was proposed in the general API document](https://docs.google.com/document/d/1ZewIIQ49qbIB1cEwuWh615JCNZi13uJl0OXR1QLNS7w/edit#heading=h.dwkgzggiee0z).
 - [x] Define the testing strategy for the Expression entities.

If possible, this should be auto-generated from code. cc @inigomedina

**Comment by IagoLast** [comment]
I think this is outdated cc @davidmanzanares @rochoa

**Comment by davidmanzanares** [comment]
I'll complete the error control regarding types
