### ISSUE TITLE
Category bucket question/comparison with Builder

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#75]
@davidmanzanares 

Heyyy,
I'm seeing two different results between Builder and the renderer when I symbolize two categories in my data.

With the renderer, I am using `buckets` to symbolize fires caused by lightning and arson:
```
width: 5
color: ramp(buckets($cause_descrip,"Lightning","Arson"),Prism)
```
[result](https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoiZmlyZV9wZXJpbWV0ZXJfY2VudHJvaWRzIiwiYiI6IiIsImMiOiJtYW1hdGFha2VsbGEiLCJkIjoiY2FydG8uY29tIiwiZSI6IndpZHRoOiA1XG5jb2xvcjogcmFtcChidWNrZXRzKCRjYXVzZV9kZXNjcmlwLFwiTGlnaHRuaW5nXCIsXCJBcnNvblwiKSxQcmlzbSlcblxuXG5cblxuIiwiZiI6eyJsbmciOi0xMjEuMTgyNTUwMTE1MjQxNjcsImxhdCI6MzguNDY4NDc5MzU0MDM5OTR9LCJnIjo1LjgxNjc2NzIxNTE0MDIxM30=)

In Builder, I'm doing the same with TurboCARTO:
```
  marker-fill: ramp([cause_descrip], (#5F4690, #f28423,rgba(50,50,50,0.8)), ("Lightning","Arson"), "=");
```
[result](https://team.carto.com/u/mamataakella/builder/c165576f-dbf0-40d6-a34d-1b06900b11c1/embed)

As you can see, I'm getting two different results... any ideas why?

thanks!

**Comment by rochoa** [comment]
Could this be related to https://github.com/CartoDB/renderer-prototype/issues/110?

**Comment by davidmanzanares** [comment]
Yes, it is completely related, and they should probably be tackled together.

**Comment by davidmanzanares** [comment]
Closing this since https://github.com/CartoDB/renderer-prototype/issues/110
