### ISSUE TITLE
How to make a classed bubble map

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#76]
@davidmanzanares 

how would I make a classed bubble map?

Following the syntax for making a classed color map, I was thinking something like:

`width: ramp(quantiles($gis_acres,5),5,20)` where `5,20` is the symbol size range.

**Comment by davidmanzanares** [comment]
`width: ramp(quantiles($gis_acres,5),5,20)` seems fine to me, but needs to be implemented.

**Comment by davidmanzanares** [comment]
We finally added it!

Check it here: https://cartodb.github.io/renderer-prototype/example/mapbox.html#eyJhIjoibmVfMTBtX3BvcHVsYXRlZF9wbGFjZXNfc2ltcGxlIiwiYiI6IiIsImMiOiJjYXJ0b2dsIiwiZCI6Imh0dHBzOi8ve3VzZXJ9LmNhcnRvLmNvbSIsImUiOiJ3aWR0aDogcmFtcChidWNrZXRzKCRwb3BfbWF4LCAxMDAwMDAsIDEwMDAwMDApLCBbMSwgMiwgNF0pICogem9vbSgpXG5jb2xvcjogcmFtcChsaW5lYXIobG9nKCRwb3BfbWF4KSwgMTMsIDE1KSwgKGFnX0dybllsKSkiLCJmIjp7ImxuZyI6LTMzLjQyMzEyODM2NzEwNTIyLCJsYXQiOjkuMzc1MzQ2MTc4MjI5NzQ4fSwiZyI6MC45NjE2OTczNjg5MzgwOTl9

**Comment by makella** [comment]
niiiiiice!
