### ISSUE TITLE
ramp($category...) vs. ramp(MODE($category...)

### ISSUE THREAD

**Issue by makella** [CartoDB/renderer-prototype#77]
@davidmanzanares 

in essence these two produce the same result, right?

```
color: ramp($cause_descrip,Prism)
color: ramp(MODE($cause_descrip),Prism)
```

is there a recommendation as to when use one of them vs. the other?

**Comment by davidmanzanares** [comment]
`color: ramp(MODE($cause_descrip),Prism)` Will allow feature aggregation for points by taking the mode of the category.

`color: ramp($cause_descrip,Prism)` Will force features with different "cause_descrip" to not be aggregated together.

**Comment by makella** [comment]
got it, thanks!
