### ISSUE TITLE
Refactor client/Windshaft

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/renderer-prototype#88]
TB(Better)D.
```
client/
    windshaft
```

- [ ] Identify what must be refactored: the main independent parts
- [ ] Decouple Windshaft communication (metadata, mvt)
- [ ] Decouple Dataframe generation (in order to add new providers)
- [ ] Decouple cache management
- [ ] Add unit tests
- [ ] ...

**Comment by rochoa** [comment]
Please, can you be more specific about what the refactor wants to accomplish? 😄

**Comment by Jesus89** [comment]
I updated the ticket a bit. But the thing is that we need to go deeper to know exactly the real state of this part and how it can be improved.
