### ISSUE TITLE
Increase CI Speed using workflows properly

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/renderer-prototype#95]
Following: https://github.com/CartoDB/renderer-prototype/pull/40
---

CircleCI has a feature called [workflows](https://circleci.com/docs/2.0/workflows/) this feature allows to define a graph of `jobs` with dependences between them.

We managed to run 3 jobs in parallel: `lint` `test:unit` and `test:acceptance`.
It would be nice to extract the common "setup" from those jobs and create a new workflow with a dependency on a common `build` job.

Somehing like:

<img width="586" alt="screen shot 2018-02-21 at 18 03 36" src="https://user-images.githubusercontent.com/2657897/36494324-07943db2-1732-11e8-9d9c-f8696c90ac74.png">

At the time of writing this the total time is `1m` which is a good CI time. This time is given by the longest task (`acceptance-tests` )

**Comment by rochoa** [comment]
Re-evaluate in the future.
